In [1]:
from pathlib import Path
import sys
import importlib

PROJECT_ROOT = Path.cwd()
while not (PROJECT_ROOT / "src/config.py").exists():
    if PROJECT_ROOT == PROJECT_ROOT.parent:
        raise FileNotFoundError("Nao encontrei src/config.py. Abra o notebook dentro do projeto.")
    PROJECT_ROOT = PROJECT_ROOT.parent

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import config
config = importlib.reload(config)
import utils
utils = importlib.reload(utils)

import pandas as pd

config.entrar_na_raiz()
config.validar_tabelas_marcas()
ANALISE_MIX_CSV = config.ANALISE_MIX_CSV
ANALISE_PRECO_FABRICANTE_CSV = config.ANALISE_PRECO_FABRICANTE_CSV

In [2]:
mix = pd.read_csv(ANALISE_MIX_CSV)
preco = pd.read_csv(ANALISE_PRECO_FABRICANTE_CSV)

In [3]:
print("MIX")
display(utils.tabela_negrito(mix.head()))

print("PRECO")
display(utils.tabela_negrito(preco.head()))

MIX

   Fabricante  Mambo  St.Marche  Paodeacucar  Total
0  3 Corações     85         63           43    191
1        L'OR     36         28           32     96
2     Nescafé     56         12           20     88
3       Pilão     30         21           23     74
4       Orfeu     33         10           23     66

PRECO

              Fabricante   mean  median    min    max  count  range
0                 Italle  15.88   13.99  13.99  18.99      9    5.0
1  Café União Pouch 250g  16.99   16.99  16.99  16.99      2    0.0
2               Floresta  19.98   19.98  19.98  19.98      4    0.0
3            Embafreezer  19.98   19.98  19.98  19.98      1    0.0
4               Bauducco  21.90   21.90  21.90  21.90      1    0.0

In [ ]:
mapa_marcas = {
    # L'OR
    "L'OR": "L'OR",
    "L'Or": "L'OR",
    "Lor": "L'OR",

    # Orfeu
    "ORFEU": "Orfeu",
    "Orfeu": "Orfeu",

    # Santa Mônica
    "Santa Monica": "Santa Mônica",
    "Santa Mônica": "Santa Mônica",

    # Bravo Café
    "Bravo Cafe": "Bravo Café",
    "Bravo Café": "Bravo Café",

    # 3 Corações
    "Tres Coracoes": "3 Corações",
    "Três": "3 Corações",
    "Tres": "3 Corações",
    "3 Corações": "3 Corações",

    # Qualitá
    "QUALITA": "Qualitá",
    "Qualitá": "Qualitá",
    "Qualitá Exclusive": "Qualitá",

    # Prima Qualitá
    "Prima Qualita": "Prima Qualitá",
    "Prima Qualitá": "Prima Qualitá",

    # Café do Ponto
    "Café Do Ponto": "Café do Ponto",
    "Café do Ponto": "Café do Ponto",
    "do Ponto": "Café do Ponto",

    # Iguaçu
    "Cafe Iguacu": "Iguaçu",
    "Iguaçu": "Iguaçu",

    # erro
    "pa": None
}

In [5]:
mix["Fabricante"] = mix["Fabricante"].replace(mapa_marcas)

# remover linhas inválidas
mix = mix[mix["Fabricante"].notna()].copy()

display(utils.tabela_negrito(mix.head(10)))

   Fabricante  Mambo  St.Marche  Paodeacucar  Total
0  3 Corações     85         63           43    191
1        L'OR     36         28           32     96
2     Nescafé     56         12           20     88
3       Pilão     30         21           23     74
4       Orfeu     33         10           23     66
5  St. Marche      0         61            0     61
6      Baggio     18         14           17     49
7        Illy     15          8           13     36
8     Melitta     24          2            4     30
9   Coffee ++     29          0            0     29

In [6]:
mix_corrigido = mix.groupby("Fabricante", as_index=False).sum()
display(utils.tabela_negrito(mix_corrigido.head(20)))

                  Fabricante  Mambo  St.Marche  Paodeacucar  Total
0                      3 Chá      0          0            2      2
1                 3 Corações     85         63           43    191
2                 Astro Cafe      0          0            5      5
3                    Aviação      2          0            0      2
4                     Baggio     18         14           17     49
5                      Baobá      0          8            0      8
6                   Bauducco      1          0            0      1
7                   Bialetti      2          0            0      2
8                 Brasileiro      1          0            0      1
9                      Bravo      0          0            1      1
10                Bravo Café      9          9            4     22
11                  C Annata      0          0            1      1
12                   Caboclo      1          0            3      4
13             Cafe Floresta      2          0            0      2
14             Caffè Corsini      9          0            0      9
15           Café Brasileiro      6          0            3      9
16  Café Fazenda Pessegueiro      0          5            0      5
17                 Café Pelé      1          0            0      1
18               Café Toledo      4          0            0      4
19     Café União Pouch 250g      0          0            2      2

In [7]:
colunas_lojas = [col for col in mix_corrigido.columns if col != "Fabricante"]

mix_corrigido["Total"] = mix_corrigido[colunas_lojas].sum(axis=1)
mix_corrigido = mix_corrigido.sort_values("Total", ascending=False)

display(utils.tabela_negrito(mix_corrigido.head(20)))

             Fabricante  Mambo  St.Marche  Paodeacucar  Total
1            3 Corações     85         63           43    382
42                 L'OR     36         28           32    192
47              Nescafé     56         12           20    176
52                Pilão     30         21           23    148
51                Orfeu     33         10           23    132
57           St. Marche      0         61            0    122
4                Baggio     18         14           17     98
38                 Illy     15          8           13     72
44              Melitta     24          2            4     60
26            Coffee ++     29          0            0     58
48  Nescafé Dolce Gusto      0          0           28     56
55              Qualitá      0          0           26     52
58            Starbucks      7         11            8     52
60                União      9          3           13     50
56         Santa Mônica     10          0           13     46
10           Bravo Café      9          9            4     44
41          Juan Valdez      7          3            5     30
21        Café do Ponto      3          4            4     22
29          Dolce Gusto      0         11            0     22
14        Caffè Corsini      9          0            0     18

In [8]:
preco["Fabricante"] = preco["Fabricante"].replace(mapa_marcas)
preco = preco[preco["Fabricante"].notna()].copy()

display(utils.tabela_negrito(preco.head()))
print(preco.columns.tolist())

              Fabricante   mean  median    min    max  count  range
0                 Italle  15.88   13.99  13.99  18.99      9    5.0
1  Café União Pouch 250g  16.99   16.99  16.99  16.99      2    0.0
2               Floresta  19.98   19.98  19.98  19.98      4    0.0
3            Embafreezer  19.98   19.98  19.98  19.98      1    0.0
4               Bauducco  21.90   21.90  21.90  21.90      1    0.0

['Fabricante', 'mean', 'median', 'min', 'max', 'count', 'range']