In [1]:
from pathlib import Path
import sys
import importlib

PROJECT_ROOT = Path.cwd()
while not (PROJECT_ROOT / "src/config.py").exists():
    if PROJECT_ROOT == PROJECT_ROOT.parent:
        raise FileNotFoundError("Nao encontrei src/config.py. Abra o notebook dentro do projeto.")
    PROJECT_ROOT = PROJECT_ROOT.parent

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import config
config = importlib.reload(config)

import pandas as pd

config.entrar_na_raiz()
mambo, marche = config.carregar_bases_lojas()

In [2]:
marche.columns

Index(['SKU', 'Titulo', 'Fabricante', 'Tipo Produto', 'Departamento',
       'Categoria', 'Sub Categoria', 'GTIN', 'Modelo', 'Bytes', 'Litros',
       'Tamanho', 'Qtde. Pacote', 'Cor', 'Peso', 'Genero', 'Volume',
       'Voltagem', 'Disponibilidade', 'Preco', 'Preço Oferta', 'Vendedor',
       'Descricao', 'Descricao_1', 'URL', 'URL Imagem', 'URL Imagem_2',
       'CLUSTER PAO'],
      dtype='str')

In [3]:
colunas_importantes_marche = [
    "SKU",
    "Titulo",
    "Fabricante",
    "Categoria",
    "Disponibilidade",
    "Preco",
    "Preço Oferta",
    "URL"
]

marche = marche[colunas_importantes_marche]

marche.head()

,SKU,Titulo,Fabricante,Categoria,Disponibilidade,Preco,Preço Oferta,URL
0,20041430,Café Solúvel NESCAFÉ Original 160g,Nescafé,Café,Indisponivel,0.0,0.0,https://marche.com.br/collections/mercearia/pr...
1,20068296,Cápsula de Café Dolce Gusto Neo Espresso Dark ...,Dolce gusto,Café,Indisponivel,0.0,0.0,https://marche.com.br/collections/mercearia/pr...
2,20068298,Cápsulas de Café Dolce Gusto Neo Lungo Cerrado...,Dolce gusto,Café,Indisponivel,0.0,0.0,https://marche.com.br/collections/mercearia/pr...
3,20068295,Cápsula de Café Dolce Gusto Neo Espresso Delic...,Dolce gusto,Café,Indisponivel,0.0,0.0,https://marche.com.br/collections/mercearia/pr...
4,20068297,Cápsula de Café Dolce Gusto Neo Espresso Sul d...,Dolce gusto,Café,Indisponivel,0.0,0.0,https://marche.com.br/collections/mercearia/pr...

In [4]:
marche.info()

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SKU              366 non-null    int64
 1   Titulo           366 non-null    str
 2   Fabricante       366 non-null    str
 3   Categoria        366 non-null    str
 4   Disponibilidade  366 non-null    str
 5   Preco            366 non-null    float64
 6   Preço Oferta     366 non-null    float64
 7   URL              366 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 23.0 KB

In [5]:
marche["Fabricante"].unique()

<StringArray>
[                 'Nescafé',              'Dolce gusto',
                  'Melitta',                     'Illy',
                    'Orfeu',               '3 Corações',
               'St. Marche',              'Juan Valdez',
                      'Lor',               'Villa Piva',
                    'Baobá',                'Starbucks',
               'Bravo Café',                    'Pilão',
                   'Baggio',              'Casa Brasil',
 'Café Fazenda Pessegueiro',              'Dolce Gusto',
            'Café Do Ponto',                    'União',
                     'Tres',                  'Havanna',
            'Café do Ponto']
Length: 23, dtype: str

In [6]:
marche["Fabricante"].value_counts()

Fabricante
St. Marche                  84
3 Corações                  65
Orfeu                       30
Lor                         29
Pilão                       23
Nescafé                     16
Starbucks                   16
Baggio                      15
Illy                        14
Dolce Gusto                 14
Baobá                        9
Bravo Café                   9
Dolce gusto                  8
Villa Piva                   7
Juan Valdez                  5
Casa Brasil                  5
Café Fazenda Pessegueiro     5
Melitta                      3
Café Do Ponto                3
União                        3
Tres                         1
Havanna                      1
Café do Ponto                1
Name: count, dtype: int64

In [7]:
marche["Preco"] = pd.to_numeric(marche["Preco"], errors="coerce")
marche["Preço Oferta"] = pd.to_numeric(marche["Preço Oferta"], errors="coerce")

In [8]:
marche["Disponibilidade"].value_counts()

Disponibilidade
Disponivel      282
Indisponivel     84
Name: count, dtype: int64

In [9]:
marche = marche[marche["Disponibilidade"] == "Disponivel"] 
marche.head()

,SKU,Titulo,Fabricante,Categoria,Disponibilidade,Preco,Preço Oferta,URL
20,20026827,Cápsulas de Café Illy Descafeinado 18 Unidades,Illy,Café,Disponivel,71.29,71.29,https://marche.com.br/collections/mercearia/pr...
21,20060012,Café L'or Torrado e Moído Equilibrado Torras G...,Lor,Café,Disponivel,30.49,30.49,https://marche.com.br/collections/mercearia/pr...
38,20055865,Cápsula de Café ORFEU Intenso Dolce Gusto 90g,Orfeu,Café,Disponivel,32.49,32.49,https://marche.com.br/collections/mercearia/pr...
39,20031287,Café em Cápsula L'or Torrado e Moído Lungo Esp...,Lor,Café,Disponivel,30.99,30.99,https://marche.com.br/collections/mercearia/pr...
42,20063958,Cápsulas de Café Baobá Especial Intenso 10 Uni...,Baobá,Café,Disponivel,35.69,35.69,https://marche.com.br/collections/mercearia/pr...

In [10]:
marche.shape

(282, 8)

In [11]:
marche["Preco"].mean()

np.float64(36.00620567375886)

In [12]:
marche.groupby("Fabricante")["Preco"].mean().sort_values()

Fabricante
Nescafé                      24.548333
Havanna                      26.900000
Tres                         26.900000
Dolce Gusto                  27.626364
Bravo Café                   29.586667
Lor                          30.343929
Baggio                       31.247143
3 Corações                   32.936935
Pilão                        33.686190
Orfeu                        34.740000
União                        36.960000
St. Marche                   39.634918
Villa Piva                   40.690000
Melitta                      41.500000
Café Fazenda Pessegueiro     43.570000
Casa Brasil                  44.334000
Baobá                        44.840000
Illy                         44.918750
Juan Valdez                  45.633333
Starbucks                    46.707273
Café Do Ponto                47.990000
Café do Ponto               165.290000
Name: Preco, dtype: float64

In [13]:
marche.groupby("Fabricante")["Preco"].mean().sort_values(ascending=False)

Fabricante
Café do Ponto               165.290000
Café Do Ponto                47.990000
Starbucks                    46.707273
Juan Valdez                  45.633333
Illy                         44.918750
Baobá                        44.840000
Casa Brasil                  44.334000
Café Fazenda Pessegueiro     43.570000
Melitta                      41.500000
Villa Piva                   40.690000
St. Marche                   39.634918
União                        36.960000
Orfeu                        34.740000
Pilão                        33.686190
3 Corações                   32.936935
Baggio                       31.247143
Lor                          30.343929
Bravo Café                   29.586667
Dolce Gusto                  27.626364
Havanna                      26.900000
Tres                         26.900000
Nescafé                      24.548333
Name: Preco, dtype: float64